// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
#if UNITY_2018_1_OR_NEWER
using Unity.Collections.LowLevel.Unsafe;
using Unity.Collections;
#endif
using Bubbles;
#pragma warning restore 0105

namespace Bubbles
{
    public static partial class Interop
    {
        #if UNITY_EDITOR
public const string NativeLib = "game_464711558";
#else
public const string NativeLib = "game";
#endif

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "add_extern")]
        public static extern int add_extern(int left, int right);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_example_array")]
        public static extern NativeArrayFloat get_example_array();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_example_list")]
        public static extern NativeListFloat get_example_list();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "allocate_native_array")]
        public static extern IntPtr allocate_native_array(uint size, uint elem_size);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "deallocate_native_array")]
        public static extern void deallocate_native_array(IntPtr data, uint size, uint elem_size);

    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct NativeArrayFloat
    {
        public uint size;
        public float value0;
        public float value1;
        public float value2;
        public float value3;
        public float value4;
        public float value5;
        public float value6;
        public float value7;
        public float value8;
        public float value9;
        public float value10;
        public float value11;
        public float value12;
        public float value13;
        public float value14;
        public float value15;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct NativeListFloat
    {
        public uint size;
        #if UNITY_2018_1_OR_NEWER
        [NativeDisableUnsafePtrRestriction]
        #endif
        public IntPtr data;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
