// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
#if UNITY_2018_1_OR_NEWER
using Unity.Collections.LowLevel.Unsafe;
using Unity.Collections;
#endif
using Bubbles;
#pragma warning restore 0105

namespace Bubbles
{
    public static partial class Interop
    {
        #if UNITY_EDITOR
public const string NativeLib = "game_996549290";
#else
public const string NativeLib = "game";
#endif

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "create_game")]
        public static extern ArenaFightGameExt create_game();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "advance_tick")]
        public static extern void advance_tick(ArenaFightGameExt game);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "register_views")]
        public static extern void register_views(ArenaFightGameExt game);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "render")]
        public static extern void render(ArenaFightGameExt game, float viewing_time, InteropDelegate_fn_SphereRenderParams sphere_render_action);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "render")]
        public static extern void render(ArenaFightGameExt game, float viewing_time, IntPtr sphere_render_action);


    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ArenaFightGameExt
    {
        #if UNITY_2018_1_OR_NEWER
        [NativeDisableUnsafePtrRestriction]
        #endif
        public IntPtr ptr;
        public ArenaGameInput inputs0;
        public ArenaGameInput inputs1;
        public ArenaGameInput inputs2;
        public ArenaGameInput inputs3;
        public ArenaGameInput inputs4;
        public ArenaGameInput inputs5;
        public ArenaGameInput inputs6;
        public ArenaGameInput inputs7;
        public ArenaGameInput inputs8;
        public ArenaGameInput inputs9;
        public ArenaGameInput inputs10;
        public ArenaGameInput inputs11;
        public ArenaGameInput inputs12;
        public ArenaGameInput inputs13;
        public ArenaGameInput inputs14;
        public ArenaGameInput inputs15;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ArenaGameInput
    {
        public uint player_id;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct SphereRenderParams
    {
        public Vec3Ext position;
        public float radius;
        public Vec3Ext color;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Vec3Ext
    {
        public float x;
        public float y;
        public float z;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void InteropDelegate_fn_SphereRenderParams(SphereRenderParams x0);



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
